# Site settings
title: Workshop on Cross-Cultural Considerations in NLP (C3NLP) @ NAACL 2025
email: c3nlp.committee@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://c3nlp.github.io/" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
